### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Drayz64** [Valentin349/Sport-Societies-Network#8]
## Registration Page
Enable the user to sign in/register, redirect them as necessary
- [x] #21

## Home Page
Display activities that the user has joined
- [x] #19 

#### List of activities
- [x] Display the startTime and duration on the right hand side of each activity in the list with the title on the left hand side
  - Achieve by creating a div _(containing startTime & duration)_  inside the button of `activityPopup.js` and styling it in CSS
- [x] Also display the number of users (e.g. 3/4) alongside the startTime and duration
  - Get the number of current users from the length of the array of members
- [x] Remove the details section of the sports page

#### Popup
- [x] Display info in the popup (duration, start time/date, members (3/4 thing) )
- [x] In the popup, upon [hovering](https://react-popup.elazizi.com/react-tooltip) over 3/4, list the names of the users who have joined the activity.
  - [x] Clicking on any of the names takes you to their profile page
- [x] #17
- [x] #24
- [x] #23 

#### Less important
- [ ] Filter out fully subscribed activities
- [ ] 2 types of activities (member and official events)
  - Different colours in the activity list
  - Only allow certain users to create official activities
  - Filter by type of activity
- [ ] Order activities according to date
- [ ] Allow creator of an activity to delete it (from the home page or in the activity list?)
- [ ] Disable / Hide / Delete activities after their date/time has passed
- [ ] Grey out fully subscribed activities in the list, but still allow them to be clicked

## useFetch hook
- [x] Change the header to use token auth (bearer)
- [x] Add response section for posting

## Testing
- [ ] [React testing](https://reactjs.org/docs/testing.html)

## Less Important
- [ ] Fix the spacing of the profile button to the edge when the screen size changes
- [ ] Log out button
  - `sessionStorage.clear();`
